/// <reference lib="webworker" />
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// Handle navigation requests
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('index.html'))
)

// Cache YouTube API requests
registerRoute(
  /^https:\/\/www\.youtube\.com\/.*/i,
  new NetworkFirst({
    cacheName: 'youtube-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 7 // 7 days
      })
    ]
  }),
  'GET'
)

// Cache YouTube images
registerRoute(
  /^https:\/\/i\.ytimg\.com\/.*/i,
  new CacheFirst({
    cacheName: 'youtube-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
      })
    ]
  }),
  'GET'
)

// Cache audio files (for better performance)
registerRoute(
  ({ request }) => request.destination === 'audio',
  new CacheFirst({
    cacheName: 'audio-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 7 // 7 days
      })
    ]
  }),
  'GET'
)

// Handle background audio playback
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  
  // Handle playback control messages
  if (event.data && event.data.type === 'PLAYBACK_CONTROL') {
    console.log('Service worker received playback control:', event.data.action)
    // Forward to all clients
    self.clients.matchAll().then(clients => {
      clients.forEach(client => {
        client.postMessage({
          type: 'PLAYBACK_STATUS',
          action: event.data.action,
          timestamp: Date.now()
        })
      })
    })
  }
})

// Handle media session events
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Keep service worker alive for background playback
self.addEventListener('install', (event) => {
  console.log('Service worker installed for background audio support')
})

// Prevent service worker from being terminated during playback
self.addEventListener('fetch', (event) => {
  // Allow all fetch requests to proceed normally
  // This ensures YouTube player continues to work
})

// Handle background sync for playback state
self.addEventListener('sync', (event) => {
  if (event.tag === 'background-playback-sync') {
    console.log('Background sync for playback')
    // This could be used to maintain playback state
  }
})

// Keep service worker active
setInterval(() => {
  // Send a message to keep the service worker alive
  self.clients.matchAll().then(clients => {
    clients.forEach(client => {
      client.postMessage({ type: 'KEEP_ALIVE' })
    })
  })
}, 30000) // Every 30 seconds