/// <reference lib="webworker" />
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// Handle navigation requests
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('index.html'))
)

// Cache YouTube API requests
registerRoute(
  /^https:\/\/www\.youtube\.com\/.*/i,
  new NetworkFirst({
    cacheName: 'youtube-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 7 // 7 days
      })
    ]
  }),
  'GET'
)

// Cache YouTube images
registerRoute(
  /^https:\/\/i\.ytimg\.com\/.*/i,
  new CacheFirst({
    cacheName: 'youtube-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
      })
    ]
  }),
  'GET'
)

// Handle background audio playback
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Handle media session events
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Prevent service worker from being terminated during playback
self.addEventListener('fetch', (event) => {
  // Allow all fetch requests to proceed normally
  // This ensures YouTube player continues to work
})